import { Inter } from "next/font/google";
import "./globals.css";
// import StoreProvider from "./Redux/store/storeProvider";
import { Toaster } from "react-hot-toast";
import TostProvider from "./components/TostProvider";
import SessionProvid from "./providers/sessionProvider";
import TeamProvider from "./providers/TeamProvider";
// import { SocketContextProvider } from "./context/SocketContext";

const clientId = process.env.NEXT_PUBLIC_CLIENT_ID;
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <>
      {/* <StoreProvider> */}

      <html lang="en">
        <body className={inter.className}>
          <SessionProvid>
            <TeamProvider>
            <TostProvider />
            {/* <SocketContextProvider> */}

            {children}
            {/* </SocketContextProvider> */}
            </TeamProvider>
          </SessionProvid>
        </body>
      </html>
      {/* </StoreProvider> */}
    </>
  );
}
